# Generated by Django 3.2 on 2022-03-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('country', models.CharField(default='N/A', max_length=255)),
                ('exchange', models.CharField(default='N/A', max_length=255)),
                ('date_founded', models.DateField(verbose_name=7)),
                ('market_cap', models.IntegerField(default=0)),
                ('company_name', models.CharField(default='N/A', max_length=255)),
                ('shareOutstanding', models.FloatField(default=0)),
                ('symbol', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('weburl', models.CharField(default='N/A', max_length=255)),
                ('logo', models.CharField(default='N/A', max_length=255)),
                ('finnhubIndustry', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='cryptoObject',
            fields=[
                ('coin_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(verbose_name=7)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(verbose_name=7)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(default='bigger', max_length=255)),
                ('initial_value', models.FloatField(default=0)),
                ('final_value', models.FloatField()),
                ('enabled', models.BooleanField(default=True)),
                ('via_mail', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.cryptoobject')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.companyprofile')),
                ('closed', models.FloatField()),
                ('high24', models.FloatField()),
                ('low24', models.FloatField()),
                ('open', models.FloatField()),
                ('previous_closed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='value',
            fields=[
                ('coin_currency', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=255)),
                ('percentage_1h', models.FloatField(blank=True, null=True)),
                ('percentage_1d', models.FloatField(blank=True, null=True)),
                ('current', models.FloatField(blank=True, null=True)),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('high_1d', models.FloatField(blank=True, null=True)),
                ('low_1d', models.FloatField(blank=True, null=True)),
                ('ath', models.FloatField(blank=True, null=True)),
                ('ath_time', models.DateTimeField(verbose_name=7)),
                ('atl', models.FloatField(blank=True, null=True)),
                ('atl_time', models.DateTimeField(verbose_name=7)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.cryptoobject')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('fav_currency', models.CharField(blank=True, default='eur', max_length=255)),
                ('favorite', models.ManyToManyField(to='registration.cryptoObject')),
                ('notification', models.ManyToManyField(to='registration.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='market_chart',
            fields=[
                ('coin_currency_day', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=255)),
                ('day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=255)),
                ('price1', models.FloatField(blank=True, null=True)),
                ('price2', models.FloatField(blank=True, null=True)),
                ('price3', models.FloatField(blank=True, null=True)),
                ('price4', models.FloatField(blank=True, null=True)),
                ('price5', models.FloatField(blank=True, null=True)),
                ('price6', models.FloatField(blank=True, null=True)),
                ('price7', models.FloatField(blank=True, null=True)),
                ('price8', models.FloatField(blank=True, null=True)),
                ('price9', models.FloatField(blank=True, null=True)),
                ('price10', models.FloatField(blank=True, null=True)),
                ('price11', models.FloatField(blank=True, null=True)),
                ('price12', models.FloatField(blank=True, null=True)),
                ('price13', models.FloatField(blank=True, null=True)),
                ('price14', models.FloatField(blank=True, null=True)),
                ('price15', models.FloatField(blank=True, null=True)),
                ('price16', models.FloatField(blank=True, null=True)),
                ('price17', models.FloatField(blank=True, null=True)),
                ('price18', models.FloatField(blank=True, null=True)),
                ('price19', models.FloatField(blank=True, null=True)),
                ('price20', models.FloatField(blank=True, null=True)),
                ('price21', models.FloatField(blank=True, null=True)),
                ('price22', models.FloatField(blank=True, null=True)),
                ('price23', models.FloatField(blank=True, null=True)),
                ('price24', models.FloatField(blank=True, null=True)),
                ('media', models.FloatField(blank=True, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.cryptoobject')),
            ],
        ),
    ]
