# Generated by Django 3.2 on 2021-04-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='crypto_id',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('high_1d_usd', models.FloatField(blank=True, null=True)),
                ('high_1d_euro', models.FloatField(blank=True, null=True)),
                ('high_1d_gbp', models.FloatField(blank=True, null=True)),
                ('high_1d_rub', models.FloatField(blank=True, null=True)),
                ('low_1d_usd', models.FloatField(blank=True, null=True)),
                ('low_1d_euro', models.FloatField(blank=True, null=True)),
                ('low_1d_gbp', models.FloatField(blank=True, null=True)),
                ('low_1d_rub', models.FloatField(blank=True, null=True)),
                ('curr_usd', models.FloatField(blank=True, null=True)),
                ('curr_euro', models.FloatField(blank=True, null=True)),
                ('curr_gbp', models.FloatField(blank=True, null=True)),
                ('curr_rub', models.FloatField(blank=True, null=True)),
                ('ath_usd', models.FloatField(blank=True, null=True)),
                ('ath_euro', models.FloatField(blank=True, null=True)),
                ('ath_gbp', models.FloatField(blank=True, null=True)),
                ('ath_rub', models.FloatField(blank=True, null=True)),
                ('atl_usd', models.FloatField(blank=True, null=True)),
                ('atl_euro', models.FloatField(blank=True, null=True)),
                ('atl_gbp', models.FloatField(blank=True, null=True)),
                ('atl_rub', models.FloatField(blank=True, null=True)),
                ('ath_time', models.DateTimeField(verbose_name=7)),
                ('atl_time', models.DateTimeField(verbose_name=7)),
                ('last_updated', models.DateTimeField(verbose_name=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('favorite', models.ManyToManyField(to='registration.crypto_id')),
            ],
        ),
    ]
