# Generated by Django 3.2 on 2021-04-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_currency',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
