# Generated by Django 3.2 on 2021-04-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto_id',
            name='ath_euro',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='ath_gbp',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='ath_rub',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='ath_time',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='ath_usd',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='atl_euro',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='atl_gbp',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='atl_rub',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='atl_time',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='atl_usd',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='curr_euro',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='curr_gbp',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='curr_rub',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='curr_usd',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='high_1d_euro',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='high_1d_gbp',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='high_1d_rub',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='high_1d_usd',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='low_1d_euro',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='low_1d_gbp',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='low_1d_rub',
        ),
        migrations.RemoveField(
            model_name='crypto_id',
            name='low_1d_usd',
        ),
        migrations.CreateModel(
            name='value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'Dollar'), ('eur', 'Euro'), ('gbp', 'Pound'), ('rub', 'Ruble')], max_length=255)),
                ('current', models.FloatField(blank=True, null=True)),
                ('high_1d', models.FloatField(blank=True, null=True)),
                ('low_1d', models.FloatField(blank=True, null=True)),
                ('ath', models.FloatField(blank=True, null=True)),
                ('ath_time', models.DateTimeField(verbose_name=7)),
                ('atl', models.FloatField(blank=True, null=True)),
                ('atl_time', models.DateTimeField(verbose_name=7)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.crypto_id')),
            ],
        ),
    ]
