# Generated by Django 3.2 on 2021-04-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210416_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='coin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='registration.crypto_id'),
        ),
    ]
