# Generated by Django 3.2 on 2021-05-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_profile_fav_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_currency',
            field=models.CharField(blank=True, default='eur', max_length=255),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.profile')),
                ('value_type', models.CharField(default='bigger', max_length=255)),
                ('intial_value', models.FloatField()),
                ('final_value', models.FloatField()),
                ('enabled', models.BooleanField(default=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.cryptoobject')),
            ],
        ),
    ]
